# Generated by Django 4.1.7 on 2023-03-17 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employe_name', models.CharField(max_length=20)),
                ('email_address', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('phone_number', models.BigIntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('is_leader', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=110)),
                ('teamleader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyadmin.employe')),
            ],
        ),
        migrations.CreateModel(
            name='AssignProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_memb', to='companyadmin.employe')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyadmin.project')),
                ('team_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader', to='companyadmin.employe')),
            ],
        ),
    ]
